### ISSUE TITLE
Connect with REST

### ISSUE THREAD

**Issue by omoya-fundaciobit** [Fundacio-Bit/bioatles-frontend#16]
A Java Backend is under development. 

One of their endpoints will return the tiles where a species can be found.

The frontend should be able to retrieve those data and draw the corresponding tiles.

We have not been able to retrieve geograhical information from grids so far. That's why we are drawing the the tiles using coordinated provided in an auxiliary JSON (dummyTileData.json).

First we will try to find out how to extract the tile coordinates from the webmap (we don't even know if such info is available or not). If we are not able we will manually or programatically calculate the coordinates for the 5x5 tiles of Eivissa and Formentera and include them in that JSON. In that case we will display only the distribution of the API results in these two islands.

**Comment by omoya-fundaciobit** [comment]
Manual calculation: 

having such geographic data for a given tile:

      "rings": [
        [1.27, 38.8809],
        [1.2134, 38.8798],
        [1.2134, 38.835],
        [1.27, 38.835]
      ]

We can calculate other tiles adding 0,0573 to the four first array parameters. That will produce the next tile coordinates in the same row from left to right.

Add also 0,001 to the second array parameters

**Comment by omoya-fundaciobit** [comment]
Connecting to the backend will be done using axios and providing a JWT (Beerar Token) for authentication.

The JWT is obtained after a Keycloack login. A keycloack server is set to manage permissions. It contains a client that redirects our REACT app to the keycloack login form if the user is not yet logged in.

The react app will be distributed as bundle associated to the server backend code.

**Comment by omoya-fundaciobit** [comment]
One row adds vertically 0,0453

**Comment by eaguado** [comment]
Added endpoint access that gets 5x5 grids of a species.
Modified access to the ArcGIS API. Use AMD modules hosted locally instead of ES modules via NPM.
